name: actionlint

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: actionlint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    permissions:
      contents: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/actionlint.yml@1acba687361415b3f5942acceb40b228bb0387fd # 0.2.4
    with:
      post_command: python3 scripts/check_action_pins.py .github/workflows
