name: scorecard

on:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecard-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: OSSF Scorecard analysis
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@71f4345cad2998a16e8e14b800eee88c68d865ac # 0.2.3
    with:
      publish_results: false
