name: scorecard

on:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecard-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: OSSF Scorecard analysis
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@ac4d1f469f5974741c7449305ffcbd5f05a5a47f # 0.5.1
    with:
      publish_results: false
